version: '3.8'

services:
  foxy_tester:
    build: .
    container_name: foxy_bt_tester
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=57
      - FASTRTPS_DEFAULT_PROFILES_FILE=/ros2_ws/fastdds_noshm.xml
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/ros2_ws
    stdin_open: true
    tty: true
    privileged: true
